/**
 * Design System Token Index
 *
 * Centralized access to all design tokens.
 * Provides typed getters for CSS variables, Tailwind theme, and component tokens.
 *
 * Source: src/tokens/tokens.yaml (W3C DTCG v1.0)
 * Generated by: Uma (UX Design Expert) via *setup task
 */

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// CORE COLOR TOKENS (Primitives)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const colors = {
  // Neutrals
  neutral: {
    0: '#ffffff',
    50: '#f3f3f3',
    100: '#cccccc',
    200: '#c1c1c1',
    300: '#999999',
    500: '#616161',
    600: '#444444',
    700: '#333333',
    900: '#000000',
  },

  // Primary Blue
  blue: {
    primary: '#007acc',
    light: '#3794ff',
  },

  // Status Colors
  red: {
    error: '#f14c4c',
    dark: '#e51400',
  },
  green: {
    success: '#5f8787',
  },
  brown: {
    primary: '#d5c4a1',
    dark: '#504945',
  },
} as const;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// SEMANTIC COLORS (Aliases with meaning)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const semanticColors = {
  background: colors.neutral[0],
  foreground: colors.neutral[900],
  border: colors.neutral[200],

  primary: colors.blue.primary,
  primaryHover: colors.blue.light,

  success: colors.green.success,
  error: colors.red.error,
  warning: colors.brown.primary,

  textPrimary: colors.neutral[900],
  textSecondary: colors.neutral[600],
  textTertiary: colors.neutral[500],

  bgSubtle: colors.neutral[50],
  bgElevated: colors.neutral[0],
} as const;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// SPACING TOKENS (Dimension)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const spacing = {
  xs: '4px',
  sm: '8px',
  md: '16px',
  lg: '24px',
  xl: '32px',
  '2xl': '48px',
  '3xl': '64px',
  '4xl': '80px',
} as const;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// TYPOGRAPHY TOKENS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const typography = {
  fontFamily: {
    base: 'system-ui, -apple-system, sans-serif',
    mono: 'Menlo, Monaco, monospace',
  },

  fontSize: {
    xs: '12px',
    sm: '14px',
    base: '16px',
    md: '18px',
    lg: '20px',
    xl: '24px',
    '2xl': '28px',
    '3xl': '32px',
    '4xl': '40px',
    '5xl': '48px',
  },

  fontWeight: {
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
} as const;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// SHADOW TOKENS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const shadows = {
  sm: '0 1px 2px rgba(0, 0, 0, 0.05)',
  base: '0 1px 3px rgba(0, 0, 0, 0.1)',
  md: '0 4px 6px rgba(0, 0, 0, 0.1)',
  lg: '0 10px 15px rgba(0, 0, 0, 0.1)',
  xl: '0 20px 25px rgba(0, 0, 0, 0.1)',
} as const;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// BORDER RADIUS TOKENS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const radius = {
  default: '4px',
  md: '8px',
  lg: '12px',
} as const;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ANIMATION TOKENS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const animation = {
  duration: {
    fast: '150ms',
    normal: '300ms',
    slow: '500ms',
  },
  easing: {
    easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
    easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
  },
} as const;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// COMPONENT TOKENS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const components = {
  button: {
    primary: {
      background: colors.blue.primary,
      color: colors.neutral[0],
      padding: `${spacing.md} ${spacing.lg}`,
      borderRadius: radius.default,
      fontWeight: typography.fontWeight.medium,
    },
    secondary: {
      background: colors.neutral[50],
      color: colors.neutral[900],
      border: `1px solid ${colors.neutral[200]}`,
      padding: `${spacing.md} ${spacing.lg}`,
      borderRadius: radius.default,
    },
    tertiary: {
      background: 'transparent',
      color: colors.blue.primary,
      padding: `${spacing.md} ${spacing.lg}`,
    },
    danger: {
      background: colors.red.error,
      color: colors.neutral[0],
      padding: `${spacing.md} ${spacing.lg}`,
      borderRadius: radius.default,
    },
  },

  input: {
    base: {
      padding: spacing.md,
      border: `1px solid ${colors.neutral[200]}`,
      borderRadius: radius.default,
      fontSize: typography.fontSize.base,
      fontFamily: typography.fontFamily.base,
    },
    focused: {
      borderColor: colors.blue.primary,
      boxShadow: `0 0 0 2px ${colors.blue.primary}20`,
    },
  },

  card: {
    base: {
      background: colors.neutral[0],
      padding: spacing.lg,
      borderRadius: radius.md,
      boxShadow: shadows.base,
    },
  },
} as const;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// UTILITY FUNCTIONS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/**
 * Get CSS variable value by key
 * Usage: getCSSVar('color-primary') returns 'var(--color-primary)'
 */
export function getCSSVar(key: string): string {
  return `var(--${key})`;
}

/**
 * Get theme object for Tailwind configuration
 * Usage: theme: getThemeTokens() in tailwind.config.ts
 */
export function getThemeTokens() {
  return {
    colors: semanticColors,
    spacing,
    fontSize: typography.fontSize,
    fontFamily: typography.fontFamily,
    boxShadow: shadows,
    borderRadius: radius,
    animation: animation.duration,
  };
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// COMPLETE TOKENS EXPORT
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const tokens = {
  colors,
  semanticColors,
  spacing,
  typography,
  shadows,
  radius,
  animation,
  components,
} as const;

export type Tokens = typeof tokens;
